### ISSUE TITLE
Comment shortcut no longer working

### ISSUE THREAD

**Issue by kakins** [mikestead/vscode-dotenv#27]
CTRL K + C used to comment lines in .env files using `#`.  Now the shortcut inserts `;` instead. 
![image](https://user-images.githubusercontent.com/14915247/133319822-9bfa7d7b-c5f7-4658-9e11-6fb1123a966b.png)

**Comment by mikestead** [comment]
Hey @kakins thanks for the report. This plugin hasn't changed for a long time, and I'm not seeing any issue with my shortcuts for commenting locally (still get the `#` prefix and on same version as you). 

Have you installed any other plugins recently that may be clashing with this one?

**Comment by giniedp** [comment]
yeah, must be an extension. I am seeing same behavior, but have lots of extension (mac). A setup with only DotENV extension works as expected (in my case another machine, windows). Just need to find out which extension was updated recently

**Comment by giniedp** [comment]
strangely even with all extensions diabled, i still have syntax highligting on .env files and the comment inserts `;`

**Comment by giniedp** [comment]
so basically my `.env` files got somehow recognized as an `ini` files. Fixed it by doing
- open a `.env` file
- change language mode from "ini" to "Environment Variables" (bottom vscode bar)

After vscode restart the file keeps being recognized as "Environment Variables".

**Comment by kakins** [comment]
Hey!  Sorry I need to subscribe to e-mail notifications for github :)  .. I will give that a try now

**Comment by kakins** [comment]
@giniedp That did it, thanks!  Man that was driving me crazy 😄
