### ISSUE TITLE
Please add configuration for files-extension

### ISSUE THREAD

**Issue by romanlex** [mikestead/vscode-dotenv#3]
Example I want .env.development or .env.prod
But in this plugin extensions is hardcoded 

Why you use .env.production (full length word) and .env.deb (short length word)

**Comment by zackyjack** [comment]
You just simply add this to the settings:

```json
"files.associations": {
    ".env.development": "dotenv",
    ".env.prod": "dotenv"
 }
```

**Comment by mikestead** [comment]
Thanks @zackyjack, @PapsOu has now added this to the README.

As far as I know you can't use pattern matching for supported file types in vscode extensions (please correct me if i'm wrong).

There are many combinations people seem to use but I've tried to add the common ones I've found supported in other related tools. You can see these [here](https://github.com/mikestead/vscode-dotenv/blob/master/package.json#L36).

If there's any specific ones you feel should be included as also popular then please do open an issue or PR.
