### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by GarrisonD** [mikestead/vscode-dotenv#33]
Hi 👋  @mikestead

Is this project looking for maintainers? You don't have free time for this project so far 🙁

**Comment by davulrich** [comment]
I think it's no longer necessary to maintain the extension because you can add the config below to your JSON settings file.
```json
"files.associations": {
  "*.env": "properties"
}
```
It works quite well.

Source - https://stackoverflow.com/questions/60299000/how-to-set-file-association-to-custom-env-filename-in-vscode-settings
