### ISSUE TITLE
 icons for env

### ISSUE THREAD

**Issue by denis-peshkov** [mikestead/vscode-dotenv#5]
Hi guys, how about standard icons for env?
I found out that you parse only *.env but how about *.env*, i.e. in react apps I have next list of env files:
.env.development
.env.production
.env.test
.env.development.local

Could you add it pls?

**Comment by mikestead** [comment]
Hey @denis-peshkov 

Not looking to add any more extensions currently. We support a fair few already that you can see here https://github.com/mikestead/vscode-dotenv/blob/master/package.json#L36

As for icons, those are defined by vscode icon packs and not related to this extension which just handles syntax highlighting.

**Comment by denis-peshkov** [comment]
@mikestead, sorry, can't understood how to highlight this files? Now they don't highlighted

**Comment by mikestead** [comment]
These extensions are supported so your files should show highlighting. 
```
.env.development
.env.production
.env.test
```

`.env.development.local` isn't so wouldn't be highlighted.
